### ISSUE TITLE
dev-env: bgp config is not loaded into BGPd process 

### ISSUE THREAD

**Issue by pperiyasamy** [metallb/metallb#1162]
While trying to bringup metallb environment using [dev-env](https://github.com/metallb/metallb/tree/main/dev-env) with `inv dev-env -p bgp -b frr -i ipv4` command, it brings up metallb controller, speaker pods and frr router container, but frr container fails to load default `/etc/frr/bgpd.conf `file content mounted by tasks.py. because of this none of the bgp speakers are able to peer with frr router and connect request fails with `getsockopt: connection refused` error.

To workaround this we may have to either manually load bgpd.conf content via vtysh conf command or run this logic as similar to this [one](https://github.com/metallb/metallb/blob/main/e2etest/pkg/frr/container/container.go#L313-L329) done for e2e tests. 

The `inv dev-env --protocol layer2` command also fails with below error and it might need tasks.py script update.
```
Configuring MetalLB with a layer 2 test environment
Traceback (most recent call last):
  File "/usr/local/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.9/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.9/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.9/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/mnt/metallb/tasks.py", line 361, in dev_env
    layer2_dev_env()
  File "/mnt/metallb/tasks.py", line 373, in layer2_dev_env
    "SERVICE_V4_RANGE", get_service_range(4))
NameError: name 'get_service_range' is not defined
```

**Comment by pperiyasamy** [comment]
I'll work on a fix.

**Comment by fedepaol** [comment]
Thanks @pperiyasamy !
